config/routes.rb
Gitty::Application.routes.draw do

  scope '_' do
    authpwn_session
    config_vars

    resources :ssh_keys

    # Users.
    get '/users' => 'users#index', as: :users
    post '/users' => 'users#create'
    get '/users/register' => 'users#new', as: :new_user
    get '/user/:user_param(.:format)' => 'users#show', as: :user,
        constraints: { user_param: /[^\/]+/ }
    get '/user/:user_param/edit(.:format)' => 'users#edit', as: :edit_user,
        constraints: { user_param: /[^\/]+/ }
    patch '/user/:user_param(.:format)' => 'users#update',
        constraints: { user_param: /[^\/]+/ }
    delete '/user/:user_param(.:format)' => 'users#destroy',
           constraints: { user_param: /[^\/]+/ }
  end

  scope '_' do
    get 'check_access.:format' => 'repositories#check_access',
        as: :repository_check_access
    post 'change_notice.:format' => 'repositories#change_notice',
         as: :repository_change_notice
  end

  # Profiles.
  get '/:profile_name(.:format)' => 'profiles#show', as: :profile,
      constraints: { profile_name: /[^_][^\/]+/ }
  patch '/:profile_name(.:format)' => 'profiles#update',
      constraints: { profile_name: /[^_][^\/]+/ }
  delete '/:profile_name(.:format)' => 'profiles#destroy',
         constraints: { profile_name: /[^_][^\/]+/ }
  scope '_' do
    resources :profiles, only: [:index, :new, :create]
    scope 'profiles' do
      get ':profile_name(.:format)' => 'profiles#show'
      get ':profile_name/edit(.:format)' => 'profiles#edit', as: :edit_profile
      patch ':profile_name(.:format)' => 'profiles#update'
      delete ':profile_name(.:format)' => 'profiles#destroy'
    end
  end

  scope ':profile_name', constraints: { profile_name: /[^_][^\/]+/ } do
    # Mis-used git-over http repository link.
    get ':repo_name.git' => 'smart_http#index',
        constraints: { repo_name: /[^\/]+/ }, format: false, as: :git_over_http

    # Repositories.
    get ':repo_name(.:format)' => 'repositories#show',
        constraints: { repo_name: /[^\/]+/ }, as: :profile_repository
    patch ':repo_name(.:format)' => 'repositories#update',
        constraints: { repo_name: /[^\/]+/ }
    delete ':repo_name(.:format)' => 'repositories#destroy',
           constraints: { repo_name: /[^\/]+/ }
    get ':repo_name/edit(.:format)' => 'repositories#edit',
        :constraints => { :repo_name => /[^\/]+/ },
        :as => :edit_profile_repository
  end
  scope '_' do
    resources :repositories, only: [:index, :new, :create]
    scope 'repositories/:profile_name' do
      get ':repo_name(.:format)' => 'repositories#show'
      get ':repo_name/edit(.:format)' => 'repositories#edit'
      patch ':repo_name(.:format)' => 'repositories#update'
      delete ':repo_name(.:format)' => 'repositories#destroy'
    end
  end

  # HTTP fetch and push.
  scope ':profile_name/:repo_name.git', constraints: {
      profile_name: /[^_\/]+/, repo_name: /[^\/]+/ } do
    post 'git-upload-pack' => 'smart_http#upload_pack'
    post 'git-receive-pack' => 'smart_http#receive_pack'
    get 'info/refs' => 'smart_http#info_refs'
    get '*path' => 'smart_http#git_file', format: false
  end

  scope ':profile_name/:repo_name',
      constraints: { profile_name: /[^_\/]+/, repo_name: /[^\/]+/ } do
    # Feed.
    get 'subscribers(.:format)' => 'feed_subscriptions#index',
        as: :subscribers_profile_repository
    post 'subscribers(.:format)' => 'feed_subscriptions#create'
    delete 'subscribers(.:format)' => 'feed_subscriptions#destroy'
    get 'feed(.:format)' => 'repositories#feed', as: :feed_profile_repository

    # Commits.
    get 'commits(/:ref_name)' => 'commits#index',
        as: :profile_repository_commits, constraints: {ref_name: /[^\/]+/ }
    get 'commit/:commit_gid(.:format)' => 'commits#show',
        as: :profile_repository_commit

    # Branches.
    get 'branches' => 'branches#index', as: :profile_repository_branches
    get 'branch/:branch_name(.:format)' => 'branches#show',
        as: :profile_repository_branch

    # Tags.
    get 'tags' => 'tags#index', as: :profile_repository_tags
    get 'tag/:tag_name' => 'tags#show', as: :profile_repository_tag,
        constraints: {tag_name: /[^\/]+/}

    # Trees.
    scope 'tree/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'trees#show', as: :profile_repository_tree
      get '/' => 'trees#show', as: :profile_repository_commit_tree
    end

    # Blobs.
    scope 'blob/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'blobs#show', as: :profile_repository_blob, format: false
    end
    scope 'raw/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'blobs#raw', as: :raw_profile_repository_blob,
                                  format: false
    end

    # Issues
    resources :issues, only: [:create]
    get 'issues' => 'issues#index', as: :profile_repository_issues
    get 'issues/new' => 'issues#new', as: :new_profile_repository_issue
    get 'issues/:issue_number' => 'issues#show', as: :profile_repository_issue
    get 'issues/:issue_number/edit(.:format)' => 'issues#edit',
        as: :edit_profile_repository_issue
    patch 'issues/:issue_number' => 'issues#update'
    delete 'issues/:issue_number' => 'issues#destroy'

    # ACLs.
    get 'acl_entries' => 'acl_entries#index', as: :profile_repository_acl_entries
    post 'acl_entries' => 'acl_entries#create'
    patch 'acl_entries/:principal_name' => 'acl_entries#update',
        as: :profile_repository_acl_entry,
        constraints: { principal_name: /[^_][^\/]+/ }
    delete 'acl_entries/:principal_name' => 'acl_entries#destroy',
        constraints: { principal_name: /[^_][^\/]+/ }
  end

  # Profile sub-resources. (must follow repository sub-resources)
  scope '_' do
    scope 'profiles/:profile_name',
          constraints: { profile_name: /[^_][^\/]+/ } do
      # ACLs.
      get 'acl_entries' => 'acl_entries#index', as: :profile_acl_entries
      post 'acl_entries' => 'acl_entries#create'
      patch 'acl_entries/:principal_name' => 'acl_entries#update',
          as: :profile_acl_entry, constraints: { principal_name: /[^_][^\/]+/ }
      delete 'acl_entries/:principal_name' => 'acl_entries#destroy',
          constraints: { principal_name: /[^_][^\/]+/ }

      # Feed.
      get 'subscribers(.:format)' => 'feed_subscriptions#index',
          as: :subscribers_profile
      post 'subscribers(.:format)' => 'feed_subscriptions#create'
      delete 'subscribers(.:format)' => 'feed_subscriptions#destroy'
    end
  end

  root to: 'session#show'
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_filter :current_user_can_read_repo,
      only: [:show, :feed, :subscribers, :subscribe, :unsubscribe]
  before_filter :current_user_can_edit_repo, only: [:edit, :update, :destroy]

  # before_filter that validates the repository's profile
  def current_user_can_charge_repo_profile
    profile_name = params[:repository][:profile_name]
    profile = Profile.where(name: profile_name).first
    bounce_user unless profile && profile.can_charge?(current_user)
  end
  private :current_user_can_charge_repo_profile
  before_filter :current_user_can_charge_repo_profile,
      only: [:create, :update]

  # GET /_/repositories
  # GET /_/repositories.json
  def index
    @repositories = current_user.repositories
    respond_to do |format|
      format.html { redirect_to session_url }
      format.json { render json: @repositories }
    end
  end

  # GET /costan/rails
  # GET /costan/rails.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @repository }
    end
  end

  # GET /_/repositories/new
  # GET /_/repositories/new.xml
  def new
    @repository = Repository.new
    @profile = current_user.profile

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @repository }
    end
  end

  # GET /costan/rails/edit
  def edit
  end

  # POST /_/repositories
  # POST /_/repositories
  def create
    @repository = Repository.new repository_params

    respond_to do |format|
      if @repository.save
        @repository.publish_creation current_user.profile
        FeedSubscription.add current_user.profile, @repository

        format.html do
          redirect_to profile_repository_url(@repository.profile, @repository),
                      notice: 'Repository was successfully created.'
        end
        format.xml do
          render xml: @repository, status: :created,
                 location: [@repository.profile, @repository]
        end
      else
        format.html { render action: "new" }
        format.xml do
          render xml: @repository.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PUT /costan/rails
  # PUT /costan/rails.xml
  def update
    respond_to do |format|
      if @repository.update_attributes repository_params
        format.html do
          redirect_to profile_repository_url(@repository.profile, @repository),
                      notice: 'Repository was successfully updated.'
        end
        format.xml  { head :ok }
      else
        @original_repository = Repository.find(@repository.id)
        format.html { render action: "edit" }
        format.xml do
          render xml: @repository.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # Parameters for repository create / update.
  def repository_params
    params.require(:repository).permit :profile_name, :name, :url, :public,
                                       :description
  end

  # GET /costan/rails/feed
  # GET /costan/rails/feed.json
  def feed
    @feed_items = @repository.recent_feed_items
    respond_to do |format|
      format.html  # feed.html.erb
      format.json { render json: @feed_items }
    end
  end

  # DELETE /costan/rails
  # DELETE /costan/rails.xml
  def destroy
    @profile = Profile.where(name: params[:profile_name]).first!
    @repository = @profile.repositories.where(name: params[:repo_name]).first!
    @repository.destroy
    @repository.publish_deletion current_user.profile

    respond_to do |format|
      format.html { redirect_to(repositories_url) }
      format.xml  { head :ok }
    end
  end

  # GET /_/check_access.json?repo_path=costan/rails.git&ssh_key_id=1&commit_access=true
  def check_access
    @repository = Repository.find_by_ssh_path params[:repo_path]
    ssh_key = SshKey.where(id: params[:ssh_key_id]).first
    @user = ssh_key && ssh_key.user
    @commit_access = params[:commit_access] &&
                     params[:commit_access] != 'false'

    message = nil
    if @repository
      if @user
        if @commit_access
          access = @repository.can_commit? @user
        else
          access = @repository.can_read? @user
        end
        unless access
          message = "You cannot " +
              (@commit_access ? 'commit to' : 'read from') +
              " #{params[:repo_path]}. Ask the owner for access."
        end
      else
        message = "The SSH key is not registered with any user."
      end
    else
      message = "Repository #{params[:repo_path]} not found."
    end

    response = message ? { access: false, message: message } : { access: true }
    respond_to do |format|
      format.json { render json: response }
    end
  end

  # POST /_/change_notice.json?repo_path=costan/rails.git&ssh_key_id=1
  protect_from_forgery except: :change_notice
  def change_notice
    @ssh_key = SshKey.find(params[:ssh_key_id])
    @repository = Repository.find_by_ssh_path params[:repo_path]

    if @repository
      @repository.record_push @ssh_key.user
      success = true
      message = 'OK'
    else
      success = false
      message = "No git repository at #{params[:repo_path]}"
    end

    respond_to do |format|
      format.json do
        render json: { success: success, message: message }
      end
    end
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
  include ProfilesHelper
  
  # Decorated link to a repository.
  def link_to_repository(repository)
    link_to_profile(repository.profile) + '/' +
        link_to(repository.name,
                profile_repository_path(repository.profile, repository))
  end
end

app/views/repositories/_bootstrap_steps.html.erb
<div class="bootstrap_steps">

<h3>Global setup</h3>

<p>
  <a href="http://git-scm.com/download">Download Git</a> and install it.
</p>

<pre>
git config --global user.name "<%= current_user.profile.display_name %>"
git config --global user.email <%= current_user.email %>
</pre>

<h3>Next steps</h3>

<pre>
mkdir <%= @repository.name %>
cd <%= @repository.name %>
git init
touch README
git add README
git commit -m 'first commit'
git remote add origin <%= @repository.ssh_uri %>
git push -u origin master
</pre>

<h3>Existing Git Repository?</h3>

<pre>
cd existing_git_repo
git remote add origin <%= @repository.ssh_uri %>
git push -u origin master
</pre>

<h3>When you're done</h3>

<%= link_to 'Continue', profile_repository_path(@profile, @repository) %>

</div>

app/views/repositories/_empty.html.erb
<p class="empty_repository">
  This repository has no contents. Point its owner to this page for instructions
  on committing some contents.
</p>
 

app/views/repositories/_form.html.erb
<%= form_for(@repository, :url => (@repository.new_record? ? @repository :
             [@profile, @original_repository || @repository])) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_name, 'Profile' %>
    <%= f.select :profile_name, current_user.chargeable_profiles.map(&:name) %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url, 'Homepage URL' %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :public, 'Public' %>
    <%= f.check_box :public %> anyone can read this repository
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/_list.html.erb
<ul class="wide_list repositories"> 
<% repositories.each do |repository| %>
  <% if repository.can_read? current_user %>
  <li>
    <%= link_to repository.name, [repository.profile, repository] %>
    [<%= repository.public ? 'public' : 'private' %>]

    <ul class="actions">
      <li>
        <%= link_to 'Delete', [repository.profile, repository],
                :method => :delete, :data => {
                :confirm => "This will permanently delete all the information in the #{repository.name} repository." } %>
      </li>
    </ul>
    
    <% if repository.description %>
    <p class="description"><%= repository.description %></p>
    <% end %>
  </li>
  <% end %>
<% end %>
</ul>

app/views/repositories/_repository.html.erb
<div class="repository">
  <p class="name">
    <%= link_to repository.profile.name, repository.profile %>
    /
    <%= link_to repository.name, [repository.profile, repository] %>
    [<%= repository.public ? 'public' : 'private' %>]
  </p>
  <% if repository.description %>
  <p class="description">
    <%= repository.description %>
  </p>
  <% else %>
  <p class="description missing">    
    This repository has no description.
    <% if repository.can_edit? current_user %>
    <%= link_to 'Add a description',
                edit_profile_repository_path(repository.profile, repository) %>
    <% end %>
  </p>
  <% end %>
  <dl class="metadata">
    <% if repository.url %>
    <dt>
      Home page
    </dt>
    <dd>
      <%= link_to repository.url, repository.url, :rel => 'nofollow' %>
    </dd>
    <% elsif repository.can_edit? current_user %>
    <dt>
      Home page
    </dt>
    <dd>
      This repository has no home page.
      <%= link_to 'Add a homepage',
              edit_profile_repository_path(repository.profile, repository) %>
    </dd>
    <% end %>
    <dt>
      Gitty page
    </dt>
    <dd>
      <%= link_to profile_repository_url(repository.profile, repository),
                  profile_repository_url(repository.profile, repository) %>
    </dd>
    <dt>
      git+http
    </dt>
    <dd>
      <%= link_to git_over_http_url(repository.profile, repository),
                  git_over_http_url(repository.profile, repository) %>
    </dd>
    <dt>
      git+ssh
    </dt>
    <dd>
      <%= repository.ssh_uri %>
    </dd>
  </dl>
  
  <ul class="actions">
    <% if repository.default_branch %>
    <li>
      <%= branch_switcher repository, @branch %>
    </li>
    <li>
      <%= tag_switcher repository, @tag %>
    </li>    
    <li>
      <%= link_to 'Source',
              contextual_tree_path(repository, @branch, @tag, @commit) %>
    </li>
    <li>      
      <%= link_to 'Commits',
              contextual_commits_path(repository, @branch, @tag, @commit) %>
    </li>
    <% else %>
    <li>
      This repository is empty.
    </li>    
    <% if repository.can_commit? current_user %>
    <li>
      <%= link_to 'Guide to committing',
              profile_repository_path(repository.profile, repository) %>
    </li>
    <% end %>
    <% end %>
    <li>
      <%= link_to 'Feed', feed_profile_repository_path(repository.profile,
                                                       repository) %>
    </li>
    <li>
      <%= link_to "Issues #{issue_counter(repository, current_user)}", 
              profile_repository_issues_path(repository.profile, repository) %>  
    </li>
    <% if repository.can_edit? current_user %>
    <li>
      <%= link_to 'Sharing',
          profile_repository_acl_entries_path(repository.profile, repository) %>
    </li>
    <li>
      <%= link_to 'Settings', edit_profile_repository_path(repository.profile,
                                                           repository) %>
    </li>
    <% end %>
    <li>
      <%= link_to pluralize(repository.subscribers.count, 'follower'),
              subscribers_profile_repository_path(repository.profile,
                                                  repository) %>      
    </li>
    <% if current_user %>
    <li>
      <% if repository.subscribed? current_user.profile %>
        <%= link_to 'Unfollow',
                subscribers_profile_repository_path(repository.profile,
                repository), :method => :delete %>
      <% else %>
        <%= link_to 'Follow',
                subscribers_profile_repository_path(repository.profile,
                repository), :method => :post %>
      <% end %>
    </li>
    <% end %>
  </ul>
</div>

app/views/repositories/edit.html.erb
<%= render @repository %>


<h2>Move Repository</h2>

<%= render 'form' %>

app/views/repositories/feed.html.erb
<%= render @repository %>

<h3>Listing feed</h3>
<%= render 'feed_items/list', :feed_items => @feed_items %>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form' %>

app/views/repositories/show.html.erb
<%= render @repository %>

<% if @repository.default_branch %>
<%= render @repository.default_branch %>

<% if readme = @repository.default_branch.commit.tree.entries.
                           where('name LIKE "readme%"').first %>
<h3>README</h3>
<%= render readme.child, :blob_path => readme.name,
        :blob_reference => @repository.default_branch %>
<% else %>
<p>No README file found. You should add one.</p>
<% end %>

<% else %>
<% if @repository.can_commit? current_user %>
<%= render 'repositories/bootstrap_steps' %>
<% else %>
<%= render 'repositories/empty' %>
<% end %>
<% end %>