config/routes.rb
Gitty::Application.routes.draw do

  scope '_' do
    authpwn_session
    config_vars

    resources :ssh_keys

    # Users.
    get '/users' => 'users#index', as: :users
    post '/users' => 'users#create'
    get '/users/register' => 'users#new', as: :new_user
    get '/user/:user_param(.:format)' => 'users#show', as: :user,
        constraints: { user_param: /[^\/]+/ }
    get '/user/:user_param/edit(.:format)' => 'users#edit', as: :edit_user,
        constraints: { user_param: /[^\/]+/ }
    patch '/user/:user_param(.:format)' => 'users#update',
        constraints: { user_param: /[^\/]+/ }
    delete '/user/:user_param(.:format)' => 'users#destroy',
           constraints: { user_param: /[^\/]+/ }
  end

  scope '_' do
    get 'check_access.:format' => 'repositories#check_access',
        as: :repository_check_access
    post 'change_notice.:format' => 'repositories#change_notice',
         as: :repository_change_notice
  end

  # Profiles.
  get '/:profile_name(.:format)' => 'profiles#show', as: :profile,
      constraints: { profile_name: /[^_][^\/]+/ }
  patch '/:profile_name(.:format)' => 'profiles#update',
      constraints: { profile_name: /[^_][^\/]+/ }
  delete '/:profile_name(.:format)' => 'profiles#destroy',
         constraints: { profile_name: /[^_][^\/]+/ }
  scope '_' do
    resources :profiles, only: [:index, :new, :create]
    scope 'profiles' do
      get ':profile_name(.:format)' => 'profiles#show'
      get ':profile_name/edit(.:format)' => 'profiles#edit', as: :edit_profile
      patch ':profile_name(.:format)' => 'profiles#update'
      delete ':profile_name(.:format)' => 'profiles#destroy'
    end
  end

  scope ':profile_name', constraints: { profile_name: /[^_][^\/]+/ } do
    # Mis-used git-over http repository link.
    get ':repo_name.git' => 'smart_http#index',
        constraints: { repo_name: /[^\/]+/ }, format: false, as: :git_over_http

    # Repositories.
    get ':repo_name(.:format)' => 'repositories#show',
        constraints: { repo_name: /[^\/]+/ }, as: :profile_repository
    patch ':repo_name(.:format)' => 'repositories#update',
        constraints: { repo_name: /[^\/]+/ }
    delete ':repo_name(.:format)' => 'repositories#destroy',
           constraints: { repo_name: /[^\/]+/ }
    get ':repo_name/edit(.:format)' => 'repositories#edit',
        :constraints => { :repo_name => /[^\/]+/ },
        :as => :edit_profile_repository
  end
  scope '_' do
    resources :repositories, only: [:index, :new, :create]
    scope 'repositories/:profile_name' do
      get ':repo_name(.:format)' => 'repositories#show'
      get ':repo_name/edit(.:format)' => 'repositories#edit'
      patch ':repo_name(.:format)' => 'repositories#update'
      delete ':repo_name(.:format)' => 'repositories#destroy'
    end
  end

  # HTTP fetch and push.
  scope ':profile_name/:repo_name.git', constraints: {
      profile_name: /[^_\/]+/, repo_name: /[^\/]+/ } do
    post 'git-upload-pack' => 'smart_http#upload_pack'
    post 'git-receive-pack' => 'smart_http#receive_pack'
    get 'info/refs' => 'smart_http#info_refs'
    get '*path' => 'smart_http#git_file', format: false
  end

  scope ':profile_name/:repo_name',
      constraints: { profile_name: /[^_\/]+/, repo_name: /[^\/]+/ } do
    # Feed.
    get 'subscribers(.:format)' => 'feed_subscriptions#index',
        as: :subscribers_profile_repository
    post 'subscribers(.:format)' => 'feed_subscriptions#create'
    delete 'subscribers(.:format)' => 'feed_subscriptions#destroy'
    get 'feed(.:format)' => 'repositories#feed', as: :feed_profile_repository

    # Commits.
    get 'commits(/:ref_name)' => 'commits#index',
        as: :profile_repository_commits, constraints: {ref_name: /[^\/]+/ }
    get 'commit/:commit_gid(.:format)' => 'commits#show',
        as: :profile_repository_commit

    # Branches.
    get 'branches' => 'branches#index', as: :profile_repository_branches
    get 'branch/:branch_name(.:format)' => 'branches#show',
        as: :profile_repository_branch

    # Tags.
    get 'tags' => 'tags#index', as: :profile_repository_tags
    get 'tag/:tag_name' => 'tags#show', as: :profile_repository_tag,
        constraints: {tag_name: /[^\/]+/}

    # Trees.
    scope 'tree/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'trees#show', as: :profile_repository_tree
      get '/' => 'trees#show', as: :profile_repository_commit_tree
    end

    # Blobs.
    scope 'blob/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'blobs#show', as: :profile_repository_blob, format: false
    end
    scope 'raw/:commit_gid', constraints: { commit_gid: /[^\/]+/ } do
      get '*path' => 'blobs#raw', as: :raw_profile_repository_blob,
                                  format: false
    end

    # Issues
    resources :issues, only: [:create]
    get 'issues' => 'issues#index', as: :profile_repository_issues
    get 'issues/new' => 'issues#new', as: :new_profile_repository_issue
    get 'issues/:issue_number' => 'issues#show', as: :profile_repository_issue
    get 'issues/:issue_number/edit(.:format)' => 'issues#edit',
        as: :edit_profile_repository_issue
    patch 'issues/:issue_number' => 'issues#update'
    delete 'issues/:issue_number' => 'issues#destroy'

    # ACLs.
    get 'acl_entries' => 'acl_entries#index', as: :profile_repository_acl_entries
    post 'acl_entries' => 'acl_entries#create'
    patch 'acl_entries/:principal_name' => 'acl_entries#update',
        as: :profile_repository_acl_entry,
        constraints: { principal_name: /[^_][^\/]+/ }
    delete 'acl_entries/:principal_name' => 'acl_entries#destroy',
        constraints: { principal_name: /[^_][^\/]+/ }
  end

  # Profile sub-resources. (must follow repository sub-resources)
  scope '_' do
    scope 'profiles/:profile_name',
          constraints: { profile_name: /[^_][^\/]+/ } do
      # ACLs.
      get 'acl_entries' => 'acl_entries#index', as: :profile_acl_entries
      post 'acl_entries' => 'acl_entries#create'
      patch 'acl_entries/:principal_name' => 'acl_entries#update',
          as: :profile_acl_entry, constraints: { principal_name: /[^_][^\/]+/ }
      delete 'acl_entries/:principal_name' => 'acl_entries#destroy',
          constraints: { principal_name: /[^_][^\/]+/ }

      # Feed.
      get 'subscribers(.:format)' => 'feed_subscriptions#index',
          as: :subscribers_profile
      post 'subscribers(.:format)' => 'feed_subscriptions#create'
      delete 'subscribers(.:format)' => 'feed_subscriptions#destroy'
    end
  end

  root to: 'session#show'
end

app/models/issue.rb
# Entity that needs to be tracked (e.g. bug or feature) associated with a repo.
class Issue < ActiveRecord::Base
  # The repository that this issue refers to.
  belongs_to :repository, inverse_of: :issues
  validates :repository, presence: true

  # The profile of the user who opened this issue.
  belongs_to :author, class_name: 'Profile', inverse_of: :issues
  validates :author, presence: true

  # One-line summary of the issue.
  validates :title, length: 1..160, presence: true

  # Full description of the issue, including repro steps, desired behavior, etc.
  validates :description, length: { maximum: 1.kilobyte }, exclusion: [nil]

  # True for issues that still require attention.
  validates :open, inclusion: { in: [true, false] }

  # True for issues that have sensitive information and so will only be seen by
  # the developers and the author.
  validates :sensitive, inclusion: { in: [true, false] }

  # Externally-visible issue ID.
  #
  # This is decoupled from "id" column to avoid leaking information about
  # the application's usage.
  validates :number, presence: true, numericality: { greater_than: 0 },
      uniqueness: { scope: :repository_id }

  # Automatically set the number
  before_validation :set_default_number, on: :create

  # Use external IDs for routes instead of IDs.
  def to_param
    number.to_s
  end

  # The next valid number that can be assigned to an issue.
  def self.next_number(repository)
    if repository && !repository.issues.empty?
      return repository.issues.order('number DESC').first.number + 1
    end
    1  # Issue numbering is 1-based.
  end

  # If the issue doesn't have a number, gives it the next available number.
  def set_default_number
    self.number ||= self.class.next_number repository
  end
end

# :nodoc: access control
class Issue
  def can_edit?(user)
    repository.can_edit?(user) || (user && user.profile == author)
  end

  def can_read?(user)
    if sensitive?
      repository.can_edit?(user) || (user && user.profile == author)
    else
      repository.can_read?(user)
    end
  end
end

# :nodoc: activity feed integration
class Issue
  # Profiles following this issue.
  has_many :subscribers, through: :subscriber_feed_subscriptions,
                         source: :profile

  # Relation backing "subscribers".
  #
  # NOTE: The :dependent => :destroy option removes the FeedSubscriptions
  #       connecting subscribers, not the actual subscribers
  has_many :subscriber_feed_subscriptions, class_name: 'FeedSubscription',
           as: :topic, inverse_of: :topic, dependent: :destroy

  # Events connected to this issue.
  has_many :feed_items, through: :feed_item_topic

  # Relation backing "feed_items".
  #
  # NOTE: The :dependent => :destroy option doesn't remove the FeedItem records,
  #       it only removes the FeedItemTopic records connecting to them.
  has_many :feed_item_topic, as: :topic, dependent: :destroy,
                             inverse_of: :topic


  # Recently created events connected with this issue.
  def recent_feed_items(limit = 100)
    feed_items.order('created_at DESC').limit(limit)
  end

  # Updates feeds to reflect that this issue was created.
  # TODO(pwnall): Filter issue feed items by reading access
  def publish_opening
    # Duplicating the profile and issue title because the issue record
    # can be deleted.
    return if sensitive?
    FeedItem.publish author, 'open_issue', self,
        [author, repository, repository.profile, self],
        profile_name: repository.profile.name, repo_name: repository.name,
        author_name: author.name, issue_title: title
  end

  # Updates feeds to reflect that this issue was closed.
  # TODO(pwnall): Filter issue feed items by reading access
  def publish_closure(author_profile)
    return if sensitive?
    FeedItem.publish author_profile, 'close_issue', self,
        [author_profile, repository, repository.profile, self],
        profile_name: repository.profile.name, repo_name: repository.name,
        author_name: author.name, issue_title: title
  end

  # Updates feeds to reflect that this issue was reopened.
  # TODO(pwnall): Filter issue feed items by reading access
  def publish_reopening(author_profile)
    # Duplicating the profile and issue title because the issue record
    # can be deleted.
    return if sensitive?
    FeedItem.publish author_profile, 'reopen_issue', self,
        [author_profile, repository, repository.profile, self],
        profile_name: repository.profile.name, repo_name: repository.name,
        author_name: author.name, issue_title: title
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :current_user_can_read_repo,
      only: [:index, :new, :create]

  def current_user_can_read_issue
    @profile = Profile.where(name: params[:profile_name]).first!
    @repository = @profile.repositories.where(name: params[:repo_name]).first!
    @issue = @repository.issues.where(number: params[:issue_number]).first!
    bounce_user unless @issue.can_read? current_user
  end
  private :current_user_can_read_issue
  before_filter :current_user_can_read_issue, only: [:show]

  def current_user_can_edit_issue
    @profile = Profile.where(name: params[:profile_name]).first!
    @repository = @profile.repositories.where(name: params[:repo_name]).first!
    @issue = @repository.issues.where(number: params[:issue_number]).first!
    bounce_user unless @issue.can_edit? current_user
  end
  private :current_user_can_edit_issue
  before_filter :current_user_can_edit_issue, only: [:edit, :update, :destroy]

  # GET /costan/rails/issues
  # GET /costan/rails/issues.xml
  def index
    @issues = @repository.issues.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @issues }
    end
  end

  # GET /costan/rails/issues/1
  # GET /costan/rails/issues/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @issue }
    end
  end

  # GET /costan/rails/issues/new
  # GET /costan/rails/issues/new.xml
  def new
    @issue = Issue.new
    @issue.repository = @repository

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @issue }
    end
  end

  # GET /costan/rails/issues/1/edit
  def edit
    respond_to do |format|
      format.html # edit.html.erb
      format.xml  { render xml: @issue }
    end
  end

  # POST /costan/rails/issues
  # POST /costan/rails/issues.xml
  def create
    @author = current_user.profile

    @issue = Issue.new issue_params
    @issue.repository = @repository
    @issue.author = @author

    respond_to do |format|
      if @issue.save
        @issue.publish_opening
        FeedSubscription.add @author, @issue
        format.html do
          redirect_to profile_repository_issues_path(@profile, @repository),
              notice: 'Issue was successfully created.'
         end
        format.xml do
          render xml: @issue, status: :created, location: @issue
        end
      else
        format.html { render action: :new }
        format.xml do
          render xml: @issue.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PUT /costan/rails/issues/1
  # PUT /costan/rails/issues/1.xml
  def update
    respond_to do |format|
      if @issue.update_attributes issue_params
        # publish issue depending on being closed or reopened
        if params[:issue].has_key? :open
          if params[:issue][:open] == true || params[:issue][:open] == "true"
            @issue.publish_reopening current_user.profile
          elsif params[:issue][:open] == false ||
                params[:issue][:open] == "false"
            @issue.publish_closure current_user.profile
          else
            raise "Unimplemented open value #{params[:issue][:open]}"
          end
        end
        format.html do
          redirect_to profile_repository_issues_path(@profile, @repository),
              notice: 'Issue was successfully updated.'
        end
        format.xml { head :no_content }
      else
        format.html { render action: "edit" }
        format.xml do
          render xml: @issue.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # Parameters for creating / updating an issue.
  def issue_params
    params.require(:issue).permit :title, :description, :open, :sensitive
  end

  # DELETE /costan/rails/issues/1
  # DELETE /costan/rails/issues/1.xml
  def destroy
    FeedSubscription.remove @issue.author, @issue
    FeedItem.where(author_id: @issue.author, target_type: "Issue",
                   target_id: @issue).destroy_all
    @issue.destroy

    respond_to do |format|
      format.html do
        redirect_to profile_repository_issues_path(@profile, @repository)
      end
      format.xml  { head :no_content }
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  # Large profile image, shown on the profile's page.
  def issue_author_image(issue)
    url = Gravatar.new(issue.author.display_email).image_url size: 20,
        secure: true, default: :mm
    image_tag url, alt: 'gravatar for issue author',
                   style: 'width: 20px; height: 20px;'
  end
  
  # Returns array of closed issues that a user can read.
  def readable_closed_issues(issues, user)
    issues.select { |i| i.can_read?(user) && !i.open? } 
  end
  
  # Returns array of open issues that a user can read.
  def readable_open_issues(issues, user)
    issues.select { |i| i.can_read?(user) && i.open? }
  end
  
  # Returns a user notification counting the number of open issues.
  def issue_counter(repository, user)
    count = readable_open_issues(repository.issues, user).length
    count == 0 ? '' : "(#{count})"
  end
end

app/views/issues/_form.html.erb
<%= form_for [@issue.repository.profile, @issue.repository, @issue] do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> 
                  prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Private" %>
    <%= f.check_box :sensitive %> visible only to committers
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/_issue.html.erb
<div class="repository_issue">
  <div class="edges">
    <% if issue.open %>
      <div class="issue_status open_issue">Open</div>
    <% else %>
      <div class="issue_status closed_issue">Closed</div>
    <% end %>
    <% if issue.sensitive? %>
      <div class="issue_status sensitive_issue"
          title="visible only to committers">Private</div>
      <br />
    <% end %>
    <% if issue.can_edit? current_user %>
    <p>
      <%= link_to 'Edit', edit_profile_repository_issue_path(
              issue.repository.profile, issue.repository, issue),
              method: :get %>
      <%= link_to 'Delete', profile_repository_issue_path(
              issue.repository.profile, issue.repository, issue),
              method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
    <% end %>
  </div>
  <div class="metadata">
    <p class="title">
      <span class="number"><%= issue.number %></span>
      <%= link_to issue.title, profile_repository_issue_path(
              issue.repository.profile, issue.repository, issue) %>
    </p>
    <p class="author">
      by <%= issue.author.name %>
    </p>
    <p class="time">
      <%= distance_of_time_in_words_to_now issue.created_at %> ago
    </p>
  </div>
</div>

app/views/issues/_issue_show.html.erb
<div class="repository_issue">
  <div class="edges">
    <% if issue.open %>
      <div class="issue_status open_issue">Open</div>
    <% else %>
      <div class="issue_status closed_issue">Closed</div>
    <% end %>
    <% if issue.sensitive? %>
      <div class="issue_status sensitive_issue"
          title="visible only to committers">Private</div>
      <br />
    <% end %>
    <% if issue.can_edit? current_user %>
    <p>
      <%= link_to 'Edit', edit_profile_repository_issue_path(
              issue.repository.profile, issue.repository, issue),
              method: :get %>
      <%= link_to 'Delete', profile_repository_issue_path(
              issue.repository.profile, issue.repository, issue),
              method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
    <p>
      <% if issue.open %>
      <%= button_to 'Close Issue', profile_repository_issue_path(
              issue.repository.profile, issue.repository, issue,
              issue: { open: false }), method: :patch,
              class: 'close_issue_button' %>
      <% else %>
      <%= button_to 'Reopen Issue', profile_repository_issue_path(
              issue.repository.profile, issue.repository, issue,
              issue: { open: true }), method: :patch,
              class: 'reopen_issue_button' %>
      <% end %>
    </p>
    <% end %>
  </div>
  <div class="metadata">
    <p class="author">
      <%= issue_author_image issue %>
      <%= issue.author.name %> &lt;<%= issue.author.display_email %>&gt;
    </p>
    <p class="description">
      <%= issue.description %>
    </p>
    <p class="time">
      <%= distance_of_time_in_words_to_now issue.created_at %> ago
    </p>
  </div>
</div>

app/views/issues/_new_issue_button.html.erb
<% if repository.can_read? current_user %>
<%= link_to 'New Issue', new_profile_repository_issue_path(
        repository.profile, @repository), :class => 'button' %>
<% end %>

app/views/issues/_no_issues.html.erb
<h2>Issues</h2>

<p>There are no issues to display.</p>

<%= render 'issues/new_issue_button', :repository => repository %>

app/views/issues/edit.html.erb
<%= render @repository %>

<h2 class="issue_header">
  Editing
  <span class="number"><%= @issue.number%></span>
</h2>

<%= render 'form' %>

app/views/issues/index.html.erb
<%= render @repository %>

<% if @issues.select { |i| i.can_read? current_user }.empty? %>
<%= render 'issues/no_issues', :repository => @repository %>
<% else %>
  <%= render 'issues/new_issue_button', :repository => @repository %>

  <% unless (issues = readable_open_issues(@issues, current_user)).empty? %>
  <h2>Open Issues</h2>
  <%= render issues %>
  <% end %>
  
  <% unless (issues = readable_closed_issues(@issues, current_user)).empty? %>
  <h2>Closed Issues</h2>
  <%= render issues %>
  <% end %>
<% end %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

app/views/issues/show.html.erb
<%= render @issue.repository %>

<h2 class="issue_header">
  <span class="number"><%= @issue.number%></span>
  <%= @issue.title %>
</h2>

<%= render 'issue_show', :issue => @issue %>